name: pizzme
description: Progetto android creato tramite framework flutter.
version: 1.0.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  curved_navigation_bar: ^0.3.1
  gradient_text: ^1.0.2
  url_launcher: ^5.4.1
  swipedetector: ^1.2.0
  shared_preferences: ^0.5.6
  firebase_auth: ^0.15.3+1
  cloud_firestore: ^0.13.0+1
  rflutter_alert: ^1.0.3
  fluttertoast: ^3.1.3
  connectivity: ^0.4.6+2
  permission_handler: ^4.2.0+hotfix.3
  flutter_sms: ^1.1.0
  http: ^0.12.0+4
  flutter_launcher_icons: ^0.7.4
  flutter_speed_dial: ^1.2.5
  provider: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_android: "images/launcher/Logo.png"
  image_path_ios: "images/launcher/Logo.png"
  adaptive_icon_background: "images/launcher/LogoBackground.png"
flutter:
  uses-material-design: true
  assets:
    - images/def_avatar.png
    - images/launcher/Logo.png
  fonts:
   - family: Roboto
     fonts:
      - asset: fonts/Roboto-Regular.ttf
